### ISSUE TITLE
RBAC and client certificate auth

### ISSUE THREAD

**Issue by GoranP** [hivemq/hivemq-file-rbac-extension#4]
Hello,

It seems it is not possible to configure HiveMQ to use both - RBAC and client certificate auth. If both are enabled then after client certificate is validated HiveMQ ask for username/password from client. That seems to be redundant.

Is there a configuration that for specific listerer I can disable RBAC file extension?

Thnx,
Goran

**Comment by SgtSilvio** [comment]
Hi @GoranP 

Sorry for the late response.
HiveMQ allows multiple security extensions to work together.
You can write your own extension in addition to the file-rbac-extension for your use case:

- Register an authenticator in the `extensionStart` method
- In your authenticator check if the client provided a client certificate
  - if yes then call `authenticateSuccessfully`
  - if no then call `nextExtensionOrDefault`
- Configure a higher priority for your extension as for the file-rbac-extension (in the hivemq-extension.xml)

Feel free to comment if you have further questions.

**Comment by frjonsen** [comment]
Is this still the case? Unfortunately I am not quite sure the idea of using multiple authenticators would work. Essentially what I would like to do is:

1. We generate client certificates with common name `"SomeUUID"`.
2. Set up broker to *require* client certificate.
3. Client connects to the broker with only the certificate using `"SomeUUID"` as client id, *no username or password*.
4. Broker verifies certificate, then verifies CN of certificate is equal to the client ID (This may have to be done in an extension we write ourselves?)
5. This RBAC extension authorizes based on the client ID.

As far as I can tell, this extension will deny the request, [because username and password are not set](https://github.com/hivemq/hivemq-file-rbac-extension/blob/master/src/main/java/com/hivemq/extensions/rbac/FileAuthAuthenticator.java#L66).

Alternatively, we could connect with *only* a username, then verify username is equal to certificate CN.

Essentially, what we would like is similar behavior as the [`use_identity_as_username` option mosquitto offers](https://mosquitto.org/man/mosquitto-conf-5.html).

I guess an alternative could be for us to fork this repository and replace the username and password check with the certificate CN check. We could also submit it as a pull request, if you'd be willing to make it configurable.
